# Generated by Django 3.0 on 2019-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelist',
            name='quote',
            field=models.TextField(),
        ),
    ]
